force-app/main/default/objects/Zoom_Account_Configuration__c/Zoom_Account_Configuration__c.object-meta.xml
<CustomObject>
    <label>Zoom Account Configuration</label>
    <nameField>
        <label>Zoom Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Account Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Account_Configuration__c/fields/Access_token__c.field-meta.xml
<CustomField>
    <fullName>Access_token__c</fullName>
    <label>Access token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Account_Configuration__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Account_Configuration__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Account_Configuration__c/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Account_Configuration__c/fields/Refresh_token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_token__c</fullName>
    <label>Refresh token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ZoomGeneratorQueueable.cls
public with sharing class ZoomGeneratorQueueable implements Queueable, Database.AllowsCallouts {
    private List<Zoom_Account_Configuration__c> configList;
    private List<Zoom_Account_Configuration__c> configForUpdateList = new List<Zoom_Account_Configuration__c>();

    public ZoomGeneratorQueueable(List<Zoom_Account_Configuration__c> configList) {
        this.configList = configList;
    }

    public void execute(QueueableContext context) {
        List<Zoom_Account_Configuration__c> zoomAccountList = [SELECT Client_Id__c, Client_secret__c, Code__c, Redirect_URI__c, Access_token__c, Refresh_token__c FROM Zoom_Account_Configuration__c WHERE Id IN: configList];
        for(Zoom_Account_Configuration__c config: zoomAccountList){
            ZoomTokenGenerator generator = new ZoomTokenGenerator(config);
            generator.generateTokens();
            configForUpdateList.add(generator.config);
        }
        update configForUpdateList;
    }
}