force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Allow_participants_to_join_anytime__c.field-meta.xml
<CustomField>
    <fullName>Allow_participants_to_join_anytime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow participants to join anytime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Approval_type__c.field-meta.xml
<CustomField>
    <fullName>Approval_type__c</fullName>
    <label>Approval type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Automatically Approve</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Manually Approve</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>No Registration Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/End_date_time__c.field-meta.xml
<CustomField>
    <fullName>End_date_time__c</fullName>
    <label>End date time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/End_times__c.field-meta.xml
<CustomField>
    <fullName>End_times__c</fullName>
    <label>End times</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Host_video__c.field-meta.xml
<CustomField>
    <fullName>Host_video__c</fullName>
    <label>Host video</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
                <label>On</label>
            </value>
            <value>
                <fullName>false</fullName>
                <default>true</default>
                <label>Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Monthly_day__c.field-meta.xml
<CustomField>
    <fullName>Monthly_day__c</fullName>
    <label>Monthly day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
                <default>true</default>
                <label>14</label>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Monthly_week__c.field-meta.xml
<CustomField>
    <fullName>Monthly_week__c</fullName>
    <label>Monthly week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>First week</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Second week</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Third week</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Fourth week</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <label>Last week</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Monthly_week_day__c.field-meta.xml
<CustomField>
    <fullName>Monthly_week_day__c</fullName>
    <label>Monthly week day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Sunday</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Monday</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Tuesday</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Wednesday</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Thursday</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Friday</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Saturday</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Participant_video__c.field-meta.xml
<CustomField>
    <fullName>Participant_video__c</fullName>
    <label>Participant video</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
                <label>On</label>
            </value>
            <value>
                <fullName>false</fullName>
                <default>true</default>
                <label>Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <label>Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Daily</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Registration_type__c.field-meta.xml
<CustomField>
    <fullName>Registration_type__c</fullName>
    <label>Registration type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Attendees register once and can attend any of the occurrences</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Attendees need to register for each occurrence to attend</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Attendees register once and can choose one or more occurrences to attend</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Repeat_every__c.field-meta.xml
<CustomField>
    <fullName>Repeat_every__c</fullName>
    <label>Repeat every</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Los_Angeles</fullName>
                <label>Pacific Time (US and Canada)</label>
            </value>
            <value>
                <fullName>Pacific/Midway</fullName>
                <label>Midway Island, Samoa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ZoomMeetingWrapper.cls
public with sharing class ZoomMeetingWrapper {
	public String topic;
	public String agenda;
	public String start_time;
	public String timezone;
	public Boolean join_before_host;
	public ZoomMeetingRecurrenceWrapper recurrence;
	public ZoomMeetingSettingsWrapper settings;

    public ZoomMeetingWrapper(Meeting__c meeting){
        this.topic = meeting.Name;
        this.agenda = meeting.Description__c;
        this.start_time = String.valueof(meeting.Start_Date__c) + String.valueof(meeting.Start_Time__c);
        this.timezone = meeting.Time_Zone__c;
        this.join_before_host = meeting.Allow_participants_to_join_anytime__c;
        ZoomMeetingSettingsWrapper settings = new ZoomMeetingSettingsWrapper(meeting);
        this.settings = settings;
        if(meeting.Recurrence__c != null){
            ZoomMeetingRecurrenceWrapper recurrence = new ZoomMeetingRecurrenceWrapper(meeting);
            this.recurrence = recurrence;
        }
    }

    private with sharing class ZoomMeetingSettingsWrapper {
        public Boolean host_video;
        public Integer registration_type;
        public Boolean participant_video;
        public Integer approval_type;

        public ZoomMeetingSettingsWrapper(Meeting__c meeting){
            if(meeting.Host_video__c!=null){
                this.host_video = Boolean.valueof(meeting.Host_video__c);
            }
            if(meeting.Registration_type__c!=null){
                this.registration_type = Integer.valueof(meeting.Registration_type__c);
            }
            if(meeting.Participant_video__c!=null){
                this.participant_video = Boolean.valueof(meeting.Participant_video__c);
            }
            if(meeting.Approval_type__c!=null){
                this.approval_type = Integer.valueof(meeting.Approval_type__c);
            }
        }
    }

    private with sharing class ZoomMeetingRecurrenceWrapper {
        public String end_date_time;
        public Integer end_times;
        public Integer monthly_day;
        public Integer monthly_week;
        public Integer monthly_week_day;
        public Integer repeat_interval;
        public Integer type;
        public String weekly_days;

        public ZoomMeetingRecurrenceWrapper(Meeting__c meeting){
            if(meeting.End_times__c!=null){
                this.end_times = Integer.valueof(meeting.End_times__c);
            }
            if(meeting.End_date_time__c!=null){
                this.end_date_time = String.valueof(meeting.End_date_time__c);
            }
            if(meeting.Monthly_day__c!=null){
                this.monthly_day = Integer.valueof(meeting.Monthly_day__c);
            }
            if(meeting.Monthly_week__c!=null){
                this.monthly_week_day = Integer.valueof(meeting.Monthly_week__c);
            }
            if(meeting.Repeat_every__c!=null){
                this.repeat_interval = Integer.valueof(meeting.Repeat_every__c);
            }
            if(meeting.Type__c!=null){
                this.type = Integer.valueof(meeting.Type__c);
            }
            if(meeting.Monthly_week_day__c!=null){
                this.weekly_days = meeting.Monthly_week_day__c;
            }
        }
    }
}